// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Zorro.Dal;
using Zorro.Dal.Models;

namespace Zorro.WebApplication.Areas.Identity.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserStore<ApplicationUser> _userStore;
        private readonly IUserEmailStore<ApplicationUser> _emailStore;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly ApplicationDbContext _context;

        public RegisterModel(
            UserManager<ApplicationUser> userManager,
            IUserStore<ApplicationUser> userStore,
            SignInManager<ApplicationUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            ApplicationDbContext applicationDbContext)
        {
            _userManager = userManager;
            _userStore = userStore;
            _emailStore = GetEmailStore();
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _context = applicationDbContext;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }


            [Required, System.ComponentModel.DisplayName("First Name")]
            [StringLength(50, ErrorMessage = "Error: First Name has a maximum of 50 Characters.")]
            public string FirstName { get; set; }

            [Required]
            [StringLength(60, ErrorMessage = "Error: Surname has a maximum of 60 Characters.")]
            public string Surname { get; set; }


            [RegularExpression(@"^(\d{10})$", ErrorMessage = "Error: Must be 10 Digits.")]
            public string Mobile { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime? BirthDate { get; set; }

        }

        // code to get users age diff from today and birthdate adapted from
        //https://stackoverflow.com/questions/9/how-do-i-calculate-someones-age-based-on-a-datetime-type-birthday
        public static int GetAge(DateTime birthDate)
        {
            DateTime today = DateTime.Now; // To avoid a race condition around midnight
            int age = today.Year - birthDate.Year;

            if (today.Month < birthDate.Month || (today.Month == birthDate.Month && today.Day < birthDate.Day))
                age--;

            return age;
        }




        public async Task OnGetAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {

            returnUrl ??= Url.Content("~/");
           
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

           //if user tries for future
            if (Input.BirthDate >= DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "You must be at least 18+ Years to Access this Service");
                return Page();
            }

            var dateOBirth = Input.BirthDate;
            var ageReturn  = GetAge((DateTime)dateOBirth);

            if(ageReturn <= 18)
            {
                ModelState.AddModelError(string.Empty, "You must be at least 18+ Years to Access this Service");
                return Page();
            }

            if (ModelState.IsValid)
            {
                var user = CreateUser();

                var key = new byte[32];
                using (var generator = RandomNumberGenerator.Create())
                    generator.GetBytes(key);
                string apiKey = Convert.ToBase64String(key);

                await _userStore.SetUserNameAsync(user, Input.Email, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, Input.Email, CancellationToken.None);
                user.FirstName = Input.FirstName;
                user.Surname = Input.Surname;
                user.BirthDate = Input.BirthDate;
                user.Mobile = Input.Mobile;
                user.Avatar = "/9j/4AAQSkZJRgABAQEBLAEsAAD/4QCeRXhpZgAASUkqAAgAAAABAA4BAgB8AAAAGgAAAAAAAABVc2VyIHByb2ZpbGUgaWNvbiB2ZWN0b3IuIEF2YXRhciBwb3J0cmFpdCBzeW1ib2wuIEZsYXQgc2hhcGUgcGVyc29uIHNpZ24gbG9nby4gQmxhY2sgc2lsaG91ZXR0ZSBpc29sYXRlZCBvbiB3aGl0ZSBiYWNrZ3JvdW5k/+EFo2h0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyI+Cgk8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgoJCTxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6SXB0YzR4bXBDb3JlPSJodHRwOi8vaXB0Yy5vcmcvc3RkL0lwdGM0eG1wQ29yZS8xLjAveG1sbnMvIiAgIHhtbG5zOkdldHR5SW1hZ2VzR0lGVD0iaHR0cDovL3htcC5nZXR0eWltYWdlcy5jb20vZ2lmdC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBsdXM9Imh0dHA6Ly9ucy51c2VwbHVzLm9yZy9sZGYveG1wLzEuMC8iICB4bWxuczppcHRjRXh0PSJodHRwOi8vaXB0Yy5vcmcvc3RkL0lwdGM0eG1wRXh0LzIwMDgtMDItMjkvIiB4bWxuczp4bXBSaWdodHM9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9yaWdodHMvIiBwaG90b3Nob3A6Q3JlZGl0PSJHZXR0eSBJbWFnZXMvaVN0b2NrcGhvdG8iIEdldHR5SW1hZ2VzR0lGVDpBc3NldElEPSIxMjcwMzY4NjE1IiB4bXBSaWdodHM6V2ViU3RhdGVtZW50PSJodHRwczovL3d3dy5pc3RvY2twaG90by5jb20vbGVnYWwvbGljZW5zZS1hZ3JlZW1lbnQ/dXRtX21lZGl1bT1vcmdhbmljJmFtcDt1dG1fc291cmNlPWdvb2dsZSZhbXA7dXRtX2NhbXBhaWduPWlwdGN1cmwiID4KPGRjOmNyZWF0b3I+PHJkZjpTZXE+PHJkZjpsaT5BbnR0aSBIZWlra2luZW48L3JkZjpsaT48L3JkZjpTZXE+PC9kYzpjcmVhdG9yPjxkYzpkZXNjcmlwdGlvbj48cmRmOkFsdD48cmRmOmxpIHhtbDpsYW5nPSJ4LWRlZmF1bHQiPlVzZXIgcHJvZmlsZSBpY29uIHZlY3Rvci4gQXZhdGFyIHBvcnRyYWl0IHN5bWJvbC4gRmxhdCBzaGFwZSBwZXJzb24gc2lnbiBsb2dvLiBCbGFjayBzaWxob3VldHRlIGlzb2xhdGVkIG9uIHdoaXRlIGJhY2tncm91bmQ8L3JkZjpsaT48L3JkZjpBbHQ+PC9kYzpkZXNjcmlwdGlvbj4KPHBsdXM6TGljZW5zb3I+PHJkZjpTZXE+PHJkZjpsaSByZGY6cGFyc2VUeXBlPSdSZXNvdXJjZSc+PHBsdXM6TGljZW5zb3JVUkw+aHR0cHM6Ly93d3cuaXN0b2NrcGhvdG8uY29tL3Bob3RvL2xpY2Vuc2UtZ20xMjcwMzY4NjE1LT91dG1fbWVkaXVtPW9yZ2FuaWMmYW1wO3V0bV9zb3VyY2U9Z29vZ2xlJmFtcDt1dG1fY2FtcGFpZ249aXB0Y3VybDwvcGx1czpMaWNlbnNvclVSTD48L3JkZjpsaT48L3JkZjpTZXE+PC9wbHVzOkxpY2Vuc29yPgoJCTwvcmRmOkRlc2NyaXB0aW9uPgoJPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KPD94cGFja2V0IGVuZD0idyI/Pgr/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFjcHJ0AAABUAAAADNkZXNjAAABhAAAAGx3dHB0AAAB8AAAABRia3B0AAACBAAAABRyWFlaAAACGAAAABRnWFlaAAACLAAAABRiWFlaAAACQAAAABRkbW5kAAACVAAAAHBkbWRkAAACxAAAAIh2dWVkAAADTAAAAIZ2aWV3AAAD1AAAACRsdW1pAAAD+AAAABRtZWFzAAAEDAAAACR0ZWNoAAAEMAAAAAxyVFJDAAAEPAAACAxnVFJDAAAEPAAACAxiVFJDAAAEPAAACAx0ZXh0AAAAAENvcHlyaWdodCAoYykgMTk5OCBIZXdsZXR0LVBhY2thcmQgQ29tcGFueQAAZGVzYwAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z2Rlc2MAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZpZXcAAAAAABOk/gAUXy4AEM8UAAPtzAAEEwsAA1yeAAAAAVhZWiAAAAAAAEwJVgBQAAAAVx/nbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAo8AAAACc2lnIAAAAABDUlQgY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKQAqQCuALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLgAusC9QMAAwsDFgMhAy0DOANDA08DWgNmA3IDfgOKA5YDogOuA7oDxwPTA+AD7AP5BAYEEwQgBC0EOwRIBFUEYwRxBH4EjASaBKgEtgTEBNME4QTwBP4FDQUcBSsFOgVJBVgFZwV3BYYFlgWmBbUFxQXVBeUF9gYGBhYGJwY3BkgGWQZqBnsGjAadBq8GwAbRBuMG9QcHBxkHKwc9B08HYQd0B4YHmQesB78H0gflB/gICwgfCDIIRghaCG4IggiWCKoIvgjSCOcI+wkQCSUJOglPCWQJeQmPCaQJugnPCeUJ+woRCicKPQpUCmoKgQqYCq4KxQrcCvMLCwsiCzkLUQtpC4ALmAuwC8gL4Qv5DBIMKgxDDFwMdQyODKcMwAzZDPMNDQ0mDUANWg10DY4NqQ3DDd4N+A4TDi4OSQ5kDn8Omw62DtIO7g8JDyUPQQ9eD3oPlg+zD88P7BAJECYQQxBhEH4QmxC5ENcQ9RETETERTxFtEYwRqhHJEegSBxImEkUSZBKEEqMSwxLjEwMTIxNDE2MTgxOkE8UT5RQGFCcUSRRqFIsUrRTOFPAVEhU0FVYVeBWbFb0V4BYDFiYWSRZsFo8WshbWFvoXHRdBF2UXiReuF9IX9xgbGEAYZRiKGK8Y1Rj6GSAZRRlrGZEZtxndGgQaKhpRGncanhrFGuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMymzLUMw0zRjN/M7gz8TQrNGU0njTYNRM1TTWHNcI1/TY3NnI2rjbpNyQ3YDecN9c4FDhQOIw4yDkFOUI5fzm8Ofk6Njp0OrI67zstO2s7qjvoPCc8ZTykPOM9Ij1hPaE94D4gPmA+oD7gPyE/YT+iP+JAI0BkQKZA50EpQWpBrEHuQjBCckK1QvdDOkN9Q8BEA0RHRIpEzkUSRVVFmkXeRiJGZ0arRvBHNUd7R8BIBUhLSJFI10kdSWNJqUnwSjdKfUrESwxLU0uaS+JMKkxyTLpNAk1KTZNN3E4lTm5Ot08AT0lPk0/dUCdQcVC7UQZRUFGbUeZSMVJ8UsdTE1NfU6pT9lRCVI9U21UoVXVVwlYPVlxWqVb3V0RXklfgWC9YfVjLWRpZaVm4WgdaVlqmWvVbRVuVW+VcNVyGXNZdJ114XcleGl5sXr1fD19hX7NgBWBXYKpg/GFPYaJh9WJJYpxi8GNDY5dj62RAZJRk6WU9ZZJl52Y9ZpJm6Gc9Z5Nn6Wg/aJZo7GlDaZpp8WpIap9q92tPa6dr/2xXbK9tCG1gbbluEm5rbsRvHm94b9FwK3CGcOBxOnGVcfByS3KmcwFzXXO4dBR0cHTMdSh1hXXhdj52m3b4d1Z3s3gReG54zHkqeYl553pGeqV7BHtje8J8IXyBfOF9QX2hfgF+Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOutCW0nLUTtYq2AbZ5tvC3aLfguFm40blKucK6O7q1uy67p7whvJu9Fb2Pvgq+hL7/v3q/9cBwwOzBZ8Hjwl/C28NYw9TEUcTOxUvFyMZGxsPHQce/yD3IvMk6ybnKOMq3yzbLtsw1zLXNNc21zjbOts83z7jQOdC60TzRvtI/0sHTRNPG1EnUy9VO1dHWVdbY11zX4Nhk2OjZbNnx2nba+9uA3AXcit0Q3ZbeHN6i3ynfr+A24L3hROHM4lPi2+Nj4+vkc+T85YTmDeaW5x/nqegy6LzpRunQ6lvq5etw6/vshu0R7ZzuKO6070DvzPBY8OXxcvH/8ozzGfOn9DT0wvVQ9d72bfb794r4Gfio+Tj5x/pX+uf7d/wH/Jj9Kf26/kv+3P9t////7QDOUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAALIcAlAAD0FudHRpIEhlaWtraW5lbhwCeAB8VXNlciBwcm9maWxlIGljb24gdmVjdG9yLiBBdmF0YXIgcG9ydHJhaXQgc3ltYm9sLiBGbGF0IHNoYXBlIHBlcnNvbiBzaWduIGxvZ28uIEJsYWNrIHNpbGhvdWV0dGUgaXNvbGF0ZWQgb24gd2hpdGUgYmFja2dyb3VuZBwCbgAYR2V0dHkgSW1hZ2VzL2lTdG9ja3Bob3Rv/9sAQwACAQEBAQECAQEBAgICAgIEAwICAgIFBAQDBAYFBgYGBQYGBgcJCAYHCQcGBggLCAkKCgoKCgYICwwLCgwJCgoK/9sAQwECAgICAgIFAwMFCgcGBwoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK/8AAEQgBoAGgAwERAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A/fygAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA8t+Nf7cX7GX7N9xJY/H79q/4c+DLqJSzWHiXxnZWdy3ssMkokY+yqTQOzPmf4g/8AByb/AMEcvADTW0X7VU+v3MLY+z+GfBOsXiv/ALswtRAR7+ZigfLI8d8Rf8HdH/BNTR7h4NG+EPxr1lR9yew8LaZEjf8AgTqUTAfVaB8jOTvv+Dw39jZJcaZ+yH8XpY/71y2jxt+S3r/zoDkYWP8AweG/sbPLjVP2Q/i9FH/etm0eVvya9T+dAcjOs8O/8HdH/BNTWLhINZ+EPxr0ZW+9Pf8AhbTJUX/wG1KViPotAcjPYvh9/wAHJf8AwRy8ftDbyftVTaBczHH2fxN4J1izWP8A3pmtTAPr5mKBcsj6Z+Cv7b/7Gn7SFxHZfAD9q74c+M7qRQwsfDXjOyvLhfZoYpTIp9ioNBNmj1GgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgBGZUUu7AADJJPAFAHxH+2F/wcL/8ABL79j6a78O3vxvPxD8TWjbJPDHwvgTVpUcEhlkug6WULKRho5J1kH9w4NBSi2fmT+0//AMHc37X/AMQGudF/ZR+AfhP4dae4ZI9Y8RzPruqYz8sqKBDbQNjqjpcKPU0FqC6nwH+0F/wUq/4KC/tUyXK/H39sr4g69Z3gxdaLDr76dpcg97Cx8m1PU/8ALLNBSSR4ZbafYWQxZ2UMXr5cYX+VAyYkKMk4+tAFabWdHtztn1W2Q+jzqP60AOh1PT7gbra9jkHrG4b+VABNqenWw3XN7FGPWRwv86AGw6zo9wdsGq2zn0SdT/WgCyCCMg5FAEN1p9hejF5ZQy46eZGGx+dAHun7Pv8AwUs/4KD/ALK0lsvwC/bL+IOhWlmMWuiz68+o6ZEPQWF951qPwjzQLlTPvz9mD/g7m/a++H7W2i/tXfALwn8RdPQKkmseG55NC1TGfmldSJradsdERLdT6ighwXQ/TX9j3/g4V/4Jf/thT2nh2x+N5+Hvia7bZH4Y+KECaTK7kgKsd0XezmZicLHHO0h/uCglxaPtxWV1DKwIIyCD1oJFoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAjurq1sbWS9vbmOGGGMvNNK4VUUDJYk8AAckmgD8yf+ChX/B0L+xp+y7LffDr9lSyX40+NIN0T3ej34g8O2EvIzJqAVvtRU4Oy1WRGwytNEwoLUG9z8T/24f8Agrj+35/wUJuruw/aD+Ol3D4XuWO34f8AhMPpuhIhOQjwI5e7APIN1JMw7EdKC1FI+a1WKCPaiqiKOABgAUFHrH7MX7C/7ZP7aN8tp+yt+zR4t8awtP5L6vpum+VpcMn9yTULgx2kTdeHlB4PFAm0j9C/2c/+DRj9tf4hQwat+0n+0B4H+G1rNGHbT9HtZvEOoxnvHIoa2t0b/aSeYDOeelBLmuh9s/BL/g0y/wCCa3w/8i8+L/i34kfEe5VR9qttU8SrpllI3fYmnRwTovsZ2PvQTzs+n/hh/wAETv8Agkz8IoFg8K/sA/DW8KDCT+KdAXXJl9xJqRnfPvnNBPM2e5+Bv2efgD8MIUt/hp8DvB/h2OP7iaF4ZtbQL9BFGuKBHYAADAFAAQCMEZBoA47xz+zx8APifE8HxL+Bvg7xEkn3013wzaXYb6iWNs0AeGfE/wD4Imf8EmPi5A0Hin9gH4a2ZcfPP4V0BdDmb3MmmmB8++c0D5mj5h+Nv/Bpj/wTY+IH2i9+D/i/4kfDm5ZT9lttL8SLqdlG3bemoxzTuo9BOp96CudnxJ+0Z/waM/ttfDyGfVv2bPj94H+JVpDEXXT9XtpvD2oyntHGrNc27n/aeeEHGeOlBSmj89f2nf2Gf2x/2L75rP8Aap/Zp8W+CYVn8lNX1PTfN0yaT+5FqEBktJW6cJKx56UFJpnlDLFPGVdVdGHIIyCKBn0r+w//AMFcv2/f+Ce9zaWH7Pnx0u5/C9qw3fD/AMWh9S0N0ByY0gdw9oCTkm1khYnqT0oE4pn7X/8ABPT/AIOhf2NP2o5bH4c/tU2K/BbxpOViS61jUBP4dv5OBmPUCqfZSSCdl0saLlVWaVjQZuDR+m1rdW19bR3tlcxzQzRh4ZonDK6kZDAjggjkEUEElABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAHzP/AMFHP+CsP7In/BMfwOms/Hjxe974n1G0M3hr4f6Dtm1fVhuKh1jJCwQBlYG4mKRjYyqWfCMDSbP52v8AgpT/AMFtP20/+Cl2o3vhfxr4mbwX8NJZT9j+GPhe9dbSWPduX+0LjCyalIMKSHCwBkDJCjZJDVRSPj2Wa3tIDLPIkUaDlmIAUUFH3R+wH/wb3f8ABQn9u2Gx8bXvgxPhZ4CvAkieL/H9pLFPdwnB8yz04bbi4BVg6vJ5EMinKzHpQS5pH7J/sVf8G1n/AATY/ZPis/EfxD8Ay/GHxZAFaTWfiNGlxYxyY+byNMUfZVXd8ymZZpUOMS0Gbk2ff2nadp+j6fBpOkWENraWsKw21tbRBI4Y1ACoqrgKoAAAHAAoJJqACgAoAKACgAoAKACgAoAKAINS03TtZ06fSNYsILu0uoWhurW5iEkc0bAhkZWBDKQSCDwQaAPgD9tX/g2q/wCCbH7V8V34j+HPgOX4O+LJgzR6z8Oo0t7CSTHy+fpjD7Ky5+ZvJWCVyeZaClNo/Gv9v3/g3z/4KE/sIRX3jW28Fp8UfAVoHkfxh4AtJZprSFdx33unHdcW2FUuzx+fBGv3ph0oNFNM+Gopre8gEsEiSxuOGUghhQUfYX/BNb/gtt+2n/wTS1Gy8L+C/EreNPhpHKPtfwx8UXrtaxR7st/Z9xhn01zliAgaAs5Z4XbBAS4pn9E3/BOT/grB+yJ/wU48DvrXwG8YPZeJ9OtRN4l+H+vbYdX0gbgpdowSs8BZlAuIS8Z3qpKvuRQyaaPpegQUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAflD/AMFnv+DkDwZ+yZf6x+y3+wzdaX4r+J9tvs/EHi6QLc6T4Sm5V41A+W9vkPBi5hhfiUuyPbkLjG+5/P18RfiN8QvjD491X4q/FrxxqnibxNrt0bjWdf1u8a4uryTAALuxzgKAqqMKiqqqAqgANdj179gv/gmx+13/AMFI/iFJ4H/Zi+HX2mwsJlTxD4y1h2ttF0UHB/f3G1i8mGBEESyTMDu2bQzKCbSP6Df+CaX/AAb0/sV/sAf2b8SPF+lp8UvihaFZh4z8U2CfZtNnBBDadYkvHaFSARKxlnB3YlVW2AMnJs++KCQoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD4G/wCCln/BvN+xV+36dS+JPg3TE+FvxQuy0x8Y+F7BPsupzkkltRsQVjuixJJlQxTk7cysq7CFKTR/Pl+3n/wTa/a6/wCCbvxCj8C/tPfDr7LY38zJ4e8Y6PI1zoutAZ/497jau2TAJMEqxzKBuKbSrENU0zyL4c/Eb4hfB7x9pXxV+EvjjVPDPibQroXGja/ol41vdWcmCCUdTnBUlWU5V1ZlYFWIIM/oH/4Iw/8ABx/4M/a1vtH/AGW/25LrS/CnxQudlnoHi2MLb6T4tm4VI2B+Wyvn6CLiKZ+IijOluAylG2p+rlBAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4R/8F2v+DibUfF99rP7Fv8AwTt8fPb6PC0lj45+K+i3WHv25WSx0qZD8sQ5WS8Q5c5EJCjzXDSMerPxbVbayt9qhIoo1+gUCg0P1H/4I3/8G5PxM/bRi0j9pL9s+21XwX8JrhEu9G8PRlrbWfFsJAZHBI3WNk/BEpAmmTmIRq8dxQRKdtj+hP4OfBj4Ufs9fDTSfg58EPh9pXhbwvoVsINK0TRbRYYIEySSFX7zMxLM7ZZ2ZmYliSQyOmoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDmPjL8FvhP+0N8NNW+Dnxx+HuleKfC+uWxg1XRNZtFmgnXIIOD911YBldcMjKrKQwBAF7H89X/BY//g3L+Jv7FUWr/tI/sZ2+reNfhLbo93rOgSFrnWfCUIG53OBuvbJBkmYDzoU5lDqj3FBrGV9z8u2W3vbfDBZYpF+oYGgs/aT/AIITf8HE+o+Eb7Rv2Lf+CiXj57jR5mjsfA3xX1q6zJYucLHY6rM5+aI8Kl4xyhwJiVPmoGcodUfu5QZhQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4R/8HE3/AAXavvF+o6//AME7f2LfGbQ6PbvLp3xX8c6XcYa/cZSbRbSRTxEOUuZVOXO6AEKJd4aRj1Z+LjNBaQZO1I0X6ACg0P3K/wCCFv8AwbnW+nwaL+2h/wAFGPAYkvnEd94H+EusW+Ushw0d7q0TD5pzwyWbDEQwZgZf3cIZyl0R+2tBmFABQAUAFABQAUAR3d3aafaS39/dRwQQRtJNNM4VI0AyWYngAAZJPSgD85f23P8Ag55/4J5/stXt74K+DF5f/GnxTalo2g8Ezxpo8Mox8suqSZiYHn5rVbnBGGANBSg2fmn8f/8Ag63/AOCmPxSuLi0+DOh+AvhdpzyE2j6Xoh1fUYlPRXuL4tbyEeotU+lBagj5y8Xf8Fuv+CuPji8a+179v3x0kjnJGkLZaan4JZ28Sj8BQPliL4Q/4Le/8Fc/A12t9oH7fvjmR0OQNXjsdSQ/VLy2lU/iKA5Yn0h+z9/wdd/8FK/hdcW9n8avDngH4o6ckgN2+o6O2j6lKo6qlxZEW8efU2j0CcEfpX+xH/wc5/8ABPD9qm8svBfxg1G/+DHiq62oLXxxNGdImlOflh1SPESr0GblbYsThVJoIcGj9GLW6tr22jvLO4SaGZA8UsThldSMhgRwQRzmgkfQAUAFABQAUAFABQB+JH/BdL/g3OhvYda/bP8A+Cc3gPZeL5l943+Euj23y3g5aS90mJR8sw5Z7NRiUZMIEg8qYNIz7n4bq0F3BkbXjdfqCKDQ/aP/AIN2P+C7N94R1HQP+Cdv7aXjNptHuHi074UeOdUuMtYucJDot3Ix5iPCW0rHKHEBJUxbAznHqj93KDMKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPyh/4OQP8Ags9f/smeDJf2Gf2W/GP2b4n+K9L3+LvEGmz/AL7wlpMy4CRup/dX1ypOw/fhhJmGxnt3IXGN9T+d1Vt7K2CqFjiiT6BQKDU/cv8A4Nzv+CFsGn2+g/8ABRn9s/wXvvpBHqHwl8D6rbcWScNFrV3Gw5nPD20TDEQ2zEeYY/JDOUuiP21oMwoAKACgAoAKACgDyP8AbX/bi/Zy/wCCfnwMv/j/APtLeNRpek2zeTp2n2yCW/1m8Klo7KzgyDNO+08ZCIoZ5GSNHdQaTZ/NR/wVD/4Ldftcf8FNtavPCetavP4I+Ffm40/4a6Fft5V3GGysmpzrtN/JkK2xgIEKqVj3AyMGqikfGqqFAVQAB0AoKFoAKACgAoARlVlKsAQeoPegD7N/4Jef8Fv/ANrn/gmZrFl4P0vVp/HPwqEoW++G2u37eXZRlss+mTtuNjJksfLAMDlmLRh2EihMopn9Kv7FX7b37Of/AAUA+Bmn/tAfs0+Nl1XSLo+TqFjcoIr/AEe8CgyWV5BkmGdNwyMlXUq8bPG6OwZNNHrdAgoAKACgAoAKACgD8SP+DjH/AIIWw3sOvf8ABRn9jDwXtvUEmofFvwRpdvxeLy0utWkajiYcvcxKMSjMwHmCXzg0jLoz8NmW3vbcqdskUq/UMDQaH9Ef/Bt//wAFnb/9rTwZF+w1+1J4x+0/E/wppe/wj4g1Gf8AfeLdJhXBWR2P72+tlA8w/fmhAmO9kuHoMpRtsfq7QQFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB8z/APBWH/go54H/AOCY/wCyJrHx41mG01HxPev/AGX8P/DVyzY1bV5FYxq4UhhBEqtNMwK4jjZVO90DA0rs/k0+I3xF8e/GH4ha58Wvir4rutd8TeJtUm1LX9ZvCPMvLqVizuQAAoycKigKihVUBVAAb7H6Vf8ABuT/AMEb4v20fiZF+2f+0l4RS4+E3gvVSnh7RtRhBh8W6zCwJDo3+tsrZsGQH5JpgIjvWO4joInK2h/RzQZBQAUAFABQAUAFAHnn7Vn7UXwd/Yw/Z/8AEv7Svx58QnTvDPhex+0XjxIHnuZGYJFbQISPMnlkZI40yAXcZIGSAErn8n//AAUZ/wCCiHx1/wCCmH7Rt78e/jNdtZ2EBktvBfg6C5Mln4b04sCsEfAEkz7Vaa4IDSuOiRpFHGG6VkeDUDCgAoAKACgAoAKACgD3v/gnF/wUU+O3/BMz9ouz+O/wZumvdOuTHbeNvBtxcmOz8SaeGJMMnBEc6bmaC4ALROTkPG8sUgJq6P6v/wBlT9qH4Pftm/s/+Gv2lfgP4hOo+GfFNgLiyeVAk9vIGKS206Any54pFeKRMnDowBIwSGLVmehUCCgAoAKACgAoAKAP5xP+DjX/AII4RfsV/E2T9s39m7wklv8ACXxrq2zX9G0+ICHwlrMzE7URf9VY3LZMYA2QzEwjYslulBrCV9D81/hz8RvH3we+IWh/Fr4VeK7rQvE3hnVIdS0DWbIjzLO6iYMjgEEMMjDIwKupZWBViCFvU/rM/wCCT3/BRzwP/wAFOP2RNH+PGiw2uneJ7J/7L+IHhq2ZsaTq8aqZFQMSxglVlmhYlsxyKrHejhQwasz6XoEFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAR3V1a2NrJe3tzHDDDGXmmlcKqKBksSeAAOSTQB/KN/wW0/4KU6j/wAFLv209T8a+F9all+GngtptE+GNnuYRy2gcfaNT2tjEl5JGsmSFYQR2yMN0ZJDaKsjzf8A4JsfsF/EL/gpH+134c/Zi8D3E1hYXO7UPGXiGKPcNF0WFl+0XPII8xiyQxKRhppo92F3MoNuyP63/gx8HPhp+z18KPD3wQ+DnhO20Lwv4W0qHTtE0q0B2QQRrtUEklnY8szsSzszMxLMSQwOmoAKACgAoAKACgAoA/m5/wCDm/8A4KUX/wC1b+1tJ+x78N/EDP8AD34OalJb6ktvKfK1bxOFMd1K46EWgZ7RARlZPtZBZXUgNYKyufmTQWFABQAUAFABQAUAFABQAUAfpt/wbH/8FKL79lP9rVP2PPiT4hZPh78YtSjt9MW4lPlaT4nKrHayoOwuwqWjgDLSfZDlVRyQiaurn9I1BkFABQAUAFABQAUAcx8aPg38NP2hvhP4h+B/xj8J22u+F/FOlTadrelXYOyeCRcHBGGRhwyupDIyqykMoIA2P5IP+Ckv7BnxD/4JuftdeI/2YfHM819Y2pXUPBviGWPaNa0WZm+z3PAA8xdrwyqBhZoZAuV2sQ3i7o9J/wCCJX/BSrUf+CaP7aemeNfFGsyx/DTxo0GifE6z3MY4rQufs+p7Vzl7OSRpMgMxgkuUUbpAQCkro/q5tbq1vrWO9srmOaGaMPDNE4ZXUjIYEcEEcgigxJKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/MX/AIOhf+ChUv7Lv7GkH7Kvw613yPGnxpW40+7e3lxLYeHYwo1CXg5Uz+ZHaLkDck9wyndDQXBXZ/N1NLBaW7TysEjiQlieigCg1P6h/wDg3p/4Jpf8MAfsV2vi/wCJHhw2nxQ+KSW+t+MxcxFZ9NtthNjpTAgFTBHIzSKRkT3E4yyqmAxk7s++KCQoAKACgAoAKACgD5+/4Knftif8MGfsC/Er9pzT5ohrWiaF9m8KxzIrrJrF3IlpY5Rv9Yi3E0buv/PNHPQGgaV2fyCyTXdzK91qN9NdXM0jSXN1cyF5JpGJZpHY8szMSSTySSaDcSgAoAKACgAoAKACgAoAKACgBY57y1lS706+mtbmGRZLa6tpSkkEikMkiMOVZWAII5BANAH9fX/BLL9sT/hvP9gX4a/tOX80R1rW9CFt4rjhRUWPWLSR7S+wg+4jXEMjov8AzzdD0IoMGrM+gaBBQAUAFABQAUAFAHwN/wAHDH/BNM/t/fsVXXjH4b+Gzd/E/wCFqXGt+DRbRFp9SttgN9pSgZLGeONXjXGTPbwDKqz5CouzP5eYpYbu3WaJg8ciAqexBFBsf0i/8GvP/BQqX9qL9jSf9lT4i655/jT4LLb6faPcS5l1Dw7IGGnyjJyxg8uS0bAO1ILdmO6agymrO5+nVBAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAIzKil3YAAZJJ4AoA/kW/4K4/tw3X/BQn9vzx1+0HYaq1z4Xhu/7C+H67yUTQrN3SCRAeVFw7TXZB6NdsOwoNoqyPU/8Ag3u/YDh/bs/4KE6Ne+NtDF54C+FiReKvF6TRbobudJcadYPkFSJblfNZGG2SGzuEPUUBJ2R/UvQYhQAUAFABQAUAFABQB+Mf/B4j8eLrSPhD8F/2YdPugE8ReJtR8T6okb4bZp1ultArjujPqUjAdN1uD1UUFwWp+D9BqFABQAUAFABQAUAFABQAUAFABQB+8H/Bnd8eLrV/hD8af2YdQugU8O+JtN8T6Wkj5bZqNu9tOqDsivpsbEdN1wT1Y0GU9z9nKCAoAKACgAoAKACgAoA/ln/4OD/2A4f2Ef8AgoTrV34J0IWfgL4pJL4q8IJDFthtJ5JcajYJgBQIblvMWNRtjgu7dB0NBtB3R5b/AMEjv24br/gnt+354F/aDv8AVWtvC813/YXxAXeQj6FeOiTyOBywt3WG7AHVrRR3NASV0f10qyuodGBBGQQeCKDEWgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD4i/wCDhf8AbCn/AGPv+CX3je98O6s1p4m+IZTwV4YkjyHSW/SQXUqsDlGjsY7yRHHSRI/XNBUVdn8ryrHBEEUBURcAdgBQbH9PX/BtZ+xVF+yf/wAE2NA+IfiPSBB4s+MMq+L9ZkdB5kdjMgXTLfd12izEc2w8pLdzCgxk7s/QSgkKACgAoAKACgAoAKAP5y/+DuPxbNq//BSrwd4QW6ZrfRfgtp8giJ4jmuNV1QuR9Uhh/IUGsNj8t6CwoAKACgAoAKACgAoAKACgAoAKAP1I/wCDRzxbNpH/AAUq8Y+EGumW31r4LahIYgeJJrfVdLKE/RJpvzNBE9j+jSgyCgAoAKACgAoAKACgD8+v+DlX9iqL9q//AIJsa98RfDmkifxZ8HpW8X6NIiDzJLGJCup2+7rtNoZJtg5eW0hFBUXZn8wzLHPEUYBkdcEdiDQbH9UP/BvR+2FN+2D/AMEvvBF74i1ZrvxN8PC/grxPJJku8tgkYtZWYnLtJYyWcjuesjyelBjJWZ9u0EhQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH89n/B3N+0+3xA/a/8AAP7KOi6iH0/4deE31jWI4pDj+1NTcBY5F6bo7W2hdT2W9b1oNYLS5+dn7C/7MV9+2j+2T8M/2VrSKdofGvi22s9Xe2P7yHS0zcahKv8AtJZw3Dj3UUFN2R/ZBp2nafo+nwaRpNjDa2lrCsNtbW8QSOGNQFVFUcKoAAAHAAoMCagAoAKACgAoAKACgAoA/ms/4OvNOurH/gq9a3FwDsvPg7oc0Gf7ovdUjP8A49G1BrDY/NagsKACgAoAKACgAoAKACgAoAKACgD9Kf8Ag1D066vv+Cr11cW4Oyz+DuuTT4/um90uMf8Aj0i0ET2P6U6DIKACgAoAKACgAoAKAIdS07T9Y0+fSNXsYbq0uoWhura4iDxzRsCrIynhlIJBB4INAH8b37c/7MV9+xd+2R8S/wBla7jnWHwT4tubPSHuT+8m0x8T6fM3+09nNbufdjQbp3R+in/Boz+0+3w//a/8ffso61qITT/iL4TTWNHjlkOP7U0xyGjjXpuktbmZ2PdbJfSgma0uf0J0GQUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/Hh/wAFKv2gpP2qf+Cgvxl+Pq6n9ss9e+IN/Hot0Okml2j/AGGwb2zaW1uce5oN0rI+9P8Ag0Y/Zzh+IX7a/wAQP2k9WsY5rX4beB4tP09pV5j1HVpmCyof7y21jdxn0FyM9RQTN6WP6G6DIKACgAoAKACgAoAKACgD+fz/AIPCfhZd6L+1r8HvjayfuPEvw6vdDVh2fTb/AO0EH8NVGPofSg0p7H5DUGgUAFABQAUAFABQAUAFABQAUAFAH68/8Ge3wsuta/a0+MPxtCfuPDXw7sdDZj3fUr/7QAPoNK5+o9aDOpsf0B0GYUAFABQAUAFABQAUAFAH88f/AAdz/s6Q/D39tj4f/tJaTYxw2vxJ8Dy6fqBiXmXUdJmVWlc/3mtr60jHqLY46Gg1g9LHwZ/wTV/aCk/ZW/4KC/Br4+tqYs7PQfiDYR61dHpHpd2/2G/b3xaXNwfqBQU1dH9h9BgFABQAUAFABQAUAFABQAUAFABQAUAFABQB5b+3F8a7j9m/9jL4sfH6xuFiuvBnw51rWLBmON1zb2UskKj3aRUUe5FA1ufxn6fbCysILMH/AFUKpn6DFBuf0gf8GmXwT/4V/wD8E1tX+L95YKtz8R/iRqV9bXW3DPZWSxaciZ7qtxa3jD3kagym9T9QqCAoAKACgAoAKACgAoAKAPzI/wCDrP8AZmuPjJ/wTetfjhoWnCXUvhL4xtNXuXSMtKdLugbC6RcdFDz2s7nstqT0FBcHZn83VBqFABQAUAFABQAUAFABQAUAFABQB/SL/wAGpn7M1x8G/wDgm9dfHDXdOEWpfFrxjd6vbu8ZWUaXagWFqjZ6qXgup0PdboHoaDKb1P03oICgAoAKACgAoAKACgAoA/L3/g7N+Cf/AAsD/gmvpHxfstPVrn4c/EjTb25utvzR2V6sunOmeytcXVmT7xrQXB6n83+oWwvbCezJ/wBbCyZ+oxQan9mH7DvxruP2kP2MvhP8fr64WW68Z/DnRdYv2U523NxZRSTKfdZGdT7g0GD3PUqBBQAUAFABQAUAFABQAUAFABQAUAFABQB8K/8AByb8QW8Af8EcvirHbXjQ3Ovz6Jo1vtP31uNYsxMn0NuJ/wAKCo/Efy2khQSe1Bsf1s/8ETvhhB8Iv+CTPwA8KwRhDefDXT9bnQfwzamp1KQH333bZ980GEtWfUdAgoAKACgAoAKACgAoAKAOd+Lvws8FfHL4VeJfgt8SdKF94e8XaDeaNrlkW2+faXMLwyoD2JR2APUHmgD+Of8Aay/Zk+IP7GP7SvjX9lj4oqzaz4J1ySwe8MWxdQtsCS1vUHZJ7d4plHUCTB5BFBundHntAwoAKACgAoAKACgAoAKACgD0L9k39mP4g/tn/tLeCv2WPhcrLrHjbXI7BbwRb10+2wZLq9cd0gt0lmYdSI8DkgUCbsj+xn4R/C3wV8DfhV4a+C3w20kWHh7wloNno2h2Qbd5FpbQpDCme5CIoz1PWgwOhoAKACgAoAKACgAoAKACgD5c/wCC2Xwwg+Ln/BJn4/8AhaeMObP4a6hrcCY+9NpijUowPffaLj3xQOPxH8kwIYAjvQbn9SX/AAbZfEFvH/8AwRy+FUVzeNNc6BPrejXG4/cW31i8EKfQW5g/Cgxl8R91UEhQAUAFABQAUAFABQAUAFABQAUAFABQB+Wf/B3R4iuNH/4Jq+ENGglwus/GvS7WdAfvImmarc/lvgQ/lQXDc/nG1mY2+j3c69UtnYfgpoNT+1X9nnwNF8MPgD4G+GtvF5cfh7wfpmmIgGNogtY4gP8Axyg5zsKACgAoAKACgAoAKACgAoAKAPyk/wCDm/8A4JP6n+1L8ILf9ub4A+F2u/iD8ONJeHxTpVlGWn8QeHlZpDsUZ33FozSTIowzxSTr87iFKC4StofzuRSxzxrNC4ZHUFWU5BHrQajqACgAoAKACgAoAKACgBssscEbTTSBUQEszHAA9aAP6Jf+DZP/AIJPan+yt8H7j9uP4/eF2tPiF8R9JSHwvpV7GVn8P+HmZZFDqcbLi7ZY5nU5ZIo7dPkczJQZTd3Y/VmggKACgAoAKACgAoAKACgAoA4/9obwND8T/gD45+GlxF5kfiLwfqemOhGdwuLWSIj/AMfoA/iq0aY3Gj2k7dXtkY/iooOg/o5/4NF/EVxrH/BNTxfo08uV0b416pawIT91H0zSrn8t87n86DKe5+plBAUAFABQAUAFABQAUAFABQAUAFABQAUAfkP/AMHh19Kn7G3wh0sH5Jfi6Zm5/iTR9QUfpIaC4bn8+mpwi40+a2bpJGUP4jFBqf3BgADAFBzhQAUAFABQAUAFABQAUAFABQAUAfgf/wAF+f8Ag381n4Xazrv7df7BngWS88J3kkl/8Q/hvo9sWl0OViWl1LT4kGXs2OWlt1Ba3Yl4wYCy2waRl0Z+OMUsU8SzQyK6MMqynII9aDQdQAUAFABQAUAFADZZYoImmnkVEQZZmOAB60Afsj/wQG/4N+9Z+Jes6H+3X+3p4FlsvC1nLFf/AA7+G+sWxWXWpVIaLUtQiYZS0U4aG2Ybp2AeQCEKlwGcpdEfvbQZhQAUAFABQAUAFABQAUAFABQAEAjBFAH8PmmQi30+G2XpHGEH4DFB0H9Bf/BnlfSv+xt8XtMJ/dxfF4TLz/E+j6ep/SMUGU9z9eKCAoAKACgAoAKACgAoAKACgAoAKACgAoA/If8A4PDbGV/2NvhDqg/1cXxeMLcfxPo+oMP0jNBcNz+fTU5hbadNcsOI4i5/AZoNT+4MEEZByDQc4UAFABQAUAFABQAUAFABQAUAFABQB+W3/BVT/g2X+BX7X2san8dv2ONY0z4XfEa+drjU9IltmHhzXpzktJLFCpexnY4LTwKysQzPA7uZKC1Nrc/Cf9rv9g/9r79g7xR/wjH7WPwG1zwkslx5Nhrk0In0nUGxkC3v4S1vKxXB8sOJFBG9FPFBomnseSAgjINAwoAKAAkAZJwPU0Aevfsg/sE/thft6eJh4a/ZP+Aut+K40n8q+1+OIW+j6ew5IuL+YrBGwGT5e8ysAdiMeKBNpH7s/wDBKz/g2b+A37Hmr6Z8df2wdX0z4pfEixkW40zTI7Vj4d0GcYKyQwzKHvZ0OSs86qqnayQRugkIZubZ+otBAUAFABQAUAFABQAUAFABQAUAFAASAMk4AoA/h80yYXOnQXK9JIg4/EZoOg/oL/4M8rGVP2Nvi9qh/wBXL8XhCvH8SaPp7H9JBQZT3P14oICgAoAKACgAoAKACgAoAKACgAoAKACgD8s/+Dujw7cax/wTU8IazBDuXRfjXpd1O4H3UfTNVtvy3zoPyoLhufzjazCbjR7uBer2zqPxU0Gp/ar+zx45i+J/wA8DfEuCXzE8ReD9M1NHBzuFxaxyg/8Aj9BznYUAFABQAUAFABQAUAFABQAUAFABQAUAUvEXhvw94w0K78L+LdBstU0y/gaG+07UbVJ4LiNhgpJG4Kup7ggg0AfF3x8/4N1f+CRnx8urnV5f2WrbwXqdx/y//DnVrnRUi/3bOBxZ5PqYCeKClJo+c/Ev/Bn3+wpezeb4R/ai+M2nKTkxXt7o90o9hjTo2x9SaB87F8Mf8Gfn7CNjKJfF/wC0/wDGfUgDkRWd9o9qh9j/AMS52x9GB96A52fR3wC/4N2/+CRvwBu7fWLX9lWz8Y6nbjm/+I2qXGtpJ7taXDmzyPUQA/pQJykz7P0Dw/oPhTRLXw14W0Sz03TrGBYbLT9Ptkhgt41GFREQBUUDoAABQSXKACgAoAKACgAoAKACgAoAKACgAoAKAOO/aH8cxfC/4AeOfiXcS+XH4d8Hanqbvn7ot7SSUn/xygEfxV6NCbfR7SBuqWyKfwUUHQf0c/8ABov4duNH/wCCani/WZ4tq6z8a9UuoGI+8iaZpVt+W+Bx+dBlPc/UyggKACgAoAKACgAoAKACgAoAKACgAoAKAPhX/g5L+HzeP/8Agjl8VZLazM1zoE2iazb7Rny1t9Ys2mf8Lcz/AIUFQ+I/ltIDAg96DY/rZ/4Im/E+D4u/8EmfgB4qgkDmz+Gthoc7g9ZtMU6bIT777Rs+9BhL4j6joEFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAHy3/wWz+J8Hwj/AOCTHx/8UzSBDefDW/0OFyfuy6mo02Mj333a498UDjufyTgADAHAoNz+pL/g20+HzeAP+COXwqkuLMw3Ovza3rNxuH+sW41i8aF/xtxB+FBjL4j7qoJCgAoAKACgAoAKACgAoAKACgAoAKACgDy79t/4K3H7SH7GfxX+AFjbrJdeM/hzrWjWIcfdubiylihYe6yMjD3AoGtGfxnafdC9sILwDHmwq+D2yM0G5/SB/wAGmPxs/wCFgf8ABNfV/g/e36tc/Dn4kalZW1ruy0dlerFqKPjsrXF1eAe8bUGU9z9QqCAoAKACgAoAKACgAoAKACgAoAKAPmf9pT/gsb/wTI/ZKvLjRvjT+2P4Qg1a0kaO68P+H7l9a1KCQfwS2unpNNCf+uiqPegai2fFPxk/4O+/2L/DBmsvgX+zT8SfGVxGxEd1q/2LRbKYdirmWecD/egU+1BXIz52+IH/AAeJftLaq7f8Kq/Yj8DaCv8AAfEPi+81Y/U+TBafl+tA/Znntx/wdy/8FQJJCbb4RfAWJM8K/hDWnIH1/tkZ/IUD5ELbf8Hcv/BT6OQG6+EPwGlTPzKnhHWkJH1/tg4/I0ByI9C+H/8AweJ/tI6U6j4qfsQeCNdX+M+HvGN5pJ+oE0F3+WfxoFyI+i/g1/wd8fsT+KTDZfHL9nD4leC7iRgJLvS0s9ZsYR3LOksM5/4Dbk0C5Gfa/wCzT/wWD/4JnftcXdvo/wAEP2xvB93q13II7Xw/rl2+j6nO5/hjs9QWGaU+6Iw96CbNH0pQIKACgAoAKACgAoAKACgAoAKACgD8vP8Ag7P+Ng8Af8E2dH+D1nfqtz8RviRptlc2u7DSWVkkuou+O6rcW1mD7yLQXBan84GoXQsrCe8Iz5ULPgd8DNBqf2Y/sQfBW4/Zv/Y0+FHwAvYFjuvBnw50XRr4KMbri3soopmPu0iux9yaDnerPUaACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/jx/wCCln7Psn7K3/BQf4zfAJdNFnaaF8Qb+XRbUDiLTLt/t1gvvi0uYBn1BoN46o+8v+DRn9ouH4efts+P/wBmzVr6OG0+JXgeLUNPErcy6jpMzMsSD1a2vruQ+oth6Cgma0P6HKDIKACgAoAKACgAoAKACgDE+IvxJ+Hfwf8ABOo/Er4seO9H8M+HdIg87Vdd1/UorOzs48gb5ZpWVEGSBkkckDvQB+TH7dv/AAdp/Aj4cS3ngX9gL4WyfEfVo90Y8beKUm0/QoX4+aKDC3d8AdykH7Mp4ZJXBoNFB9T8iv2vf+Crf/BQj9ueS6s/2iP2m9futCutyt4N8Pzf2VoojJz5T2lttW5UdmuTM/8AtGgtRSPneC3gtYhDbQpGi9ERQAPwFAx9ABQAUAFABQAUAMnt7e6iMNzAkiHqjqCD+BoA+jv2Qf8AgrP/AMFDv2GZbWy/Z+/ab12PQbXaq+DPEsv9raMYgc+UltclvsqnubZoXP8AeoE4pn67fsIf8HZ37P3xOksvAn7fHwzl+GmsyBYz4z8NpNqOgTvz80sIDXViCdqgYuEHLPMgFBm4PofrH8P/AIieAPiz4M0/4jfCzxxpHiXw9q8Hn6VrugalFeWd5FkjfFNEzJIuQRlSRkGgg2KACgAoAKACgAoAKACgAoA/ni/4O5f2jIviH+214B/Zs0m+jmtPhr4Hkv8AUFibmLUdWmVniceq21lZyD0FyfU0GsFofB3/AATT/Z9k/ap/4KD/AAZ+ATaaLy0134g2EutWpHEumWj/AG6/X2zaW04z6kUFS0R/YdQYBQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH89v/AAdzfswN8P8A9r7wB+1dounBNP8AiL4TfR9YkijOP7U0yQFZJG6bpLW6iRR3Wyb0oNIPSx+dX7DP7Tl9+xf+2R8NP2qbOWdYfBPi22vdXS2GZJtMfMGoQr/tSWc1yg93FBbV0f2Q6bqWnazp1vq+kX8N1aXUKTWt1byh45o2AZXVhwykEEEcEGgwJqACgAoAKACgAoAKAPgz/gq//wAF8/2Yf+CbUd38KvCscXxE+LptwYfBWlXyrb6QWGUk1S5UMLYbfnEChp3BQ7ERxKAqMWz+eL9t/wD4KIftef8ABRPx8PHf7U/xWuNWgtrlptE8KaeGttE0XOeLW0DEBgDt86QyTsoAaRsCg1SSPE6BhQAUAFABQAUAFABQAUAFABQAUAe4fsNf8FGf2vv+CdHjz/hNv2WvipNptpc3Kza34Q1NWudD1rGMi5tNyjcQAvnRNHOq5CyKCQQTSZ/Q9/wSj/4L1/su/wDBSqG0+F2vJH8Pfi4LdmuPA2rXyvDqpQZeXTLkhRdrtBcwkLOgVyUZE81gylFo+7qCQoAKACgAoAKACgCDU9T07RdNuNY1i/htbS0gea6uriUJHDGoLM7MeFUAEkngAUAfxvftyftO3/7aP7Y3xL/aqvZJzF428W3N7pKXX+sh0xMQafC3+1HZw26H3Q0G6VlY/Rb/AINGf2YG+IH7X3j/APau1rTg+n/Drwmmj6PJLGcf2pqchLSRt03R2trKjDst6vrQRN6WP6EqDMKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA+Iv+DhX9j2f9sL/AIJf+N7Hw7pLXfib4elPGvhiOPJd5bBJDdRKoGXaSxkvI0QdZHj9KCouzP5XlaOeIOpDI65B7EGg2P6ef+Dar9taL9q//gmzoPw68R6uJ/FnwdlXwjrMbuPMksYkDaZcbeu02hjg3nl5bSY0GM1Zn6C0EhQAUAFABQAUAfib/wAFuP8Ag5Jm8O3mtfsgf8E3PGMTahE0lj4w+L1g4kSzYZWS00huVebqrXvKx8iHMmJog0jDufhxc3N1fXk+paheTXN1dTvPd3VzM0ks8rsWeR3YlndmJYsSSSSSc0GgygAoAKACgAoAKACgAoAKACgAoAKACgAoAks7u902/t9V0u/uLS7s7hLizvLSdopreZGDJLG6kMjqwDKykEEAggigD9zf+CI3/ByO3i660X9kD/gpB4uhi1aVo7Hwf8XL11jj1BiQsdpqx4WOfoqXfCS8CXbJmWYM5R6o/augzCgAoAKACgAoA/Pj/g5X/bWi/ZR/4Js678N/DmriDxZ8YpW8I6PGjjzI7CVC2qXG3rtFpvg3jlJLyE0FQV2fzEM0cERdiFRFyT2AFBsf1Q/8G9X7Hs37Hv8AwS/8EWPiLSWtPE3xCL+NfE8cmQ6S36Rm1iZSMo0djHZxuh6SJJ60GMndn27QSFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAIyq6lWUEEYII60AfyL/8Fcv2H7n/AIJ7/t++Ov2fLDSWtfC893/b3w/bYQj6HeO7wRoTyRbus1oSeS1ox7ig3i7o9Q/4N8f2/If2Ef8AgoTotr4210WfgL4pJF4V8YPNLthtJpJc6dfvkhVENy3ltIx2xwXdw/YUCmro/qZoMQoAKACgAoA/Cn/g4k/4Lu6h4h1TX/8Agnd+xT40e3061kl074r+OtKuMPcyDKTaLZyqflRTlLmVTljugUgCXcGkY9WfixHHHFGsUSBVUYVVGABQaC0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUANkjjmjaKZAysMMrDII9KAP2u/4N2f+C7mpaZqmgf8E7v21vGj3FpdPFp3wo8d6rcZeKQ4SHRbyVj8wPCW0rHOcQMTmLAZyj1R+6FBmFABQAUAFAH8sn/BwV+35B+3h/wUJ1qLwTrn2zwF8L0l8K+D3hl3Q3cscudQv0wSpE1yvlrIp2yQWlu3eg2grI8x/wCCRn7D1z/wUJ/b98C/s+X+lNc+F4Lv+3viA20lE0KzdHnjfHIFw7Q2gI5DXansaAk7I/roVVRQqqAAMAAdKDEWgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/MX/g6F/4J6zftR/saQftU/DnQzP40+Cy3GoXSW8eZL/w7KFOoRcDLGDy47tck7UguFUbpqC4OzP5upYoLu3aGVQ8cqEMOzAig1P6hv8Ag3m/4KW/8N/fsV2vg34keJDd/FD4WJb6J4xNzKWn1O22EWOqsTksZ442SRs5M9vOcKrJkMZKzPvmgkKACgD8t/8Ag4+/4LFX/wCxh8MU/Y5/Zp8YNa/FfxzpjSa1rFhJibwposm5DMjj/V3lxh0hI+aJVkmyjCAuFwjd6n85MMUcESwxIFVRhQO1BqOoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgBssUc8ZilXKsMEUAf0d/8G4v/BYq9/bV+Fr/ALIP7Sfi9rr4teBdNWTS9Xv5MzeLNFTaguGc/wCsu4CUjnz80itHNl2abYGUo2P1DoICgAoA+BP+Dhz/AIKWn9gT9iu58E/DbxIbT4ofFNLjRPB5tpSs+mWuwC+1VSMFTDHIqRsDkT3ELAMqvgKirs/l7iigs7dYYlCRxIAoHAUAUGx/SL/wa9f8E9Jf2XP2NJ/2qfiLoZg8afGlbfULVLiPEmn+HYgx0+LkZUz+ZJdtgjck9urDdDQZTd2fp1QQFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQBHdWttfW0lle20c0M0ZSaGVAyupGCpB4II4INAH8o3/Bbb/gmtqP/AATS/bT1PwX4X0aWP4aeNGn1v4Y3exvLitS4+0aZuOcvZySLHjLMYJLZ2O6QgBtF3R5t/wAE2v28/iF/wTd/a68OftPeBbea/sbXdp/jHw9FJtGtaLMy/aLbqB5gKJNExOFmhjLZXcpBtXR/W/8ABb4y/DT9ob4T+Hvjj8HPFltrnhfxTpUOo6JqtoTtngkXIyDhkccqyMAyMrKwDKQAweh09AHjv7fH7Z3w2/4J/wD7KHi79qf4nYntfDth/wASzSEnEcur6jKRHa2URwSGllZVLYOxN8jDajEA0rs/kQ+Onxw+KH7THxm8TftB/GvxG2reLPGGrSajrd82QpkbAWKNSTshijVIo484SONFHCig3SscpQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAdZ8B/jn8Uv2Y/jT4Y/aF+CXiNtJ8V+D9Wj1HRb0Z2F1yrwygEF4ZY2eGVMgPHI6nhqAauj+vD9gz9sz4a/t+/speEf2p/hd+4s/Edh/xMdJecSS6RqEZMd1YynAy0Uquu7ADrtkUbXUkMGrM9goEcv8avjN8M/wBnf4S+Ifjl8ZPFltofhfwtpUuo63qt2TtggjXJwBlncnCqigs7MqqCzAEDc/kg/wCCkX7ePxD/AOCkP7XXiP8Aaf8AHcE1jZ3ZXT/B/h6STcNE0WFm+zW3UjzDveaVgcNNNKVwu1QG6Vkelf8ABEn/AIJq6h/wUt/bT0zwX4o0aWX4aeC2g1v4nXe1hHLahz9n0zcMYe8kjaMjKsII7l1O6MAgpOyP6ubW1trG2jsrK3jhhhjCRRRIFVFAwFAHAAHAAoMSSgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD5o/4Kwf8E5PA/8AwU4/ZE1j4Da1Na6d4nsn/tT4f+JblWxpGrxqwjZyoJMEqs0MygNmOVmUb0RlBp2Z/Jn8Rvhz4++D3xC1z4S/FXwpdaF4m8M6pNpuv6NegeZZ3UTFXQkEhhkZV1JV1KspKsCQ3P0n/wCDcv8A4LHxfsVfE6P9jP8AaR8Wpb/CXxrq2/QNZ1GYLD4S1mZgNzu3+qsrlsCQn5IZiJjsWS4egiUb6n9HlBkfzo/8HT//AAUDn/aE/a1sP2KfAWuGTwh8IGE+vrBLmK+8Szw/OTglW+yW0ghU8MktxdoegoNYLS5+WNBYUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+qH/Bq//wAFBZ/2fv2sdQ/Yl8fa6Y/CHxec3Hh5Z5cRWPiWCH5cZIVftdtH5LHlmktrRB1OQia0uf0WUGR/OF/wcZ/8Fj4v21/ifJ+xr+zf4tS4+EngnVt+u6xp8wMPi3WYWI3K68S2Vs2RGR8k0oMw3qlu9BrCNtT82fhz8OfH3xh+IWh/CX4VeFLrXfE3ibVIdN0DRrIDzLy6lYKiAkgKMnLOxCooZmIVSQFn9Zn/AASf/wCCcngf/gmR+yHo/wABdFmtNR8T3j/2p8QPEtsjf8TfV5FUSMhYBhBEqrDCpC4jiUsN7OzBg3dn0vQIKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD8o/8Ag4//AOCMN9+1r4Ml/bk/Zb8Hfafih4U0vZ4t0DToP33i3SYVyGjRR+9vrZQfLH35ogYRvZLdAFxlbc/ncVre8twylZIpF+oYGg1P2E/4JD/8HIT/ALOH7KHin9nH9sK8uNZ1PwH4Jvbv4OeILvzZW1h7e3Zrbw/duoZlfcESC4b5THmN2VkQyhnKGuh+RnijxX4r8e+KdV8fePddm1XXtf1S51PXdUuTmS9vbiVpp53/ANp5Hdj7tQaFGgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgC94X8V+K/APirSvH/AIC12bSte0DVLbU9C1S2OJLK9t5VmgnQ/wB5JERh7rQB+uf/AAV6/wCDkJ/2kP2UvC37OP7Ht5caNqXjzwTZXfxj1+182JtIe5t1Nz4ftHYKzOGLpPcL8ojxGjMzuYgzjCz1Px7ZreztyzFY4ok+gUCg0P6I/wDg3A/4Iw337JXgyL9uT9qTwd9m+KHivS9nhLw/qMH77wlpMy5LSIw/dX1ypHmD78MREJ2M9whDKUr6H6uUEBQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Ef/BxP/wAEJr7wjqOv/wDBRL9i3wY02j3Dy6j8V/A2l2+XsZDl5tatI1HMR5e5iUZQ7pwCpl2BpCXRn4vI6SIJI2DKwyCDwRQaC0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAjukSGSRwqqMsxPAFAH7Rf8ABuz/AMEJb/xZqWgf8FEf21PBbwaRbPFqPwo8Darb4e9kGGi1m8iYcRA4e2iYZc7ZyAoi3hnOXRH7t0GYUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Ef/AAXZ/wCDdjUfCN9rP7aX/BO3wC9xo8zSX3jn4UaLa5exY5aS+0qFB80R5Z7NRlDkwgqfKQNIz6M/F2GaK4iWaCQOjDKspyCKDQdQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA2aaK3iaaeQIijLMxwBQB+0f/BCX/g3Z1LxZf6L+2p/wUR8BPbaRA8d94G+FGs2u2S9cYaK+1WJh8sQ4aOzYZc4MwCjynDOU+iP3boMwoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPyi/wCCz3/BuB4M/a0v9Y/ak/YattL8KfE+58y88QeEZCttpPi2blnkUj5bK+c9ZeIpn5lCM73AC4ytofz8/Eb4c/EL4PePtV+FXxa8D6p4Z8TaFdG31nQNbs2t7q0kwCA6MM4KkMrDKurKykqQSGu5jUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAGz8Ofhz8QvjD4+0n4VfCXwPqnibxNrt0LfRtA0Sza4uryTBJCIozgKCzMcKiqzMQqkgA/oH/4Iw/8G4Hgz9kq+0f9qT9uS20vxX8ULbZeeH/CUZW40nwlNwySMT8t7fIeRLzFC/MQdkS4IZSlfY/VyggKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPmj/AIKOf8Env2RP+CnHgdNF+PHhB7LxPp1qYfDXxA0HbDq+kjcWCLIQVngLMxNvKHjO9mUK+HUGm0fzs/8ABSr/AIIlftp/8E0dRvfFHjXwy3jT4aRyn7H8TvC9k7WkUe7av9oW+WfTXOVBLloCzhUndsgBqpJnx+rBgGUgg9CKChaACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAEZlVSzEADqT2oA+wf+Cav/BEn9tP/AIKW6hZeKfBfhpvBfw0llH2v4neKLJ1tZY92G/s+3ysmpOMMAUKwBkKvMjYBCXJI/ol/4Jyf8En/ANkP/gmR4HfRfgL4Oe88T6jaCHxL8QNd2zavq/zBijSABYIAyqRbwhIxsViGfLsGTbZ9L0CCgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAI7q1tb61ksr22jmhmjKTQyoGV1IwVIPBBHBBoA/Mn/goV/wa8/saftRS33xF/ZUvl+C3jSfdK9po9gJ/DuoS8nEmnhl+yljgb7Vo0XLM0MrUFqbW5+J/wC3D/wSN/b9/wCCe11d3/7QfwLu5vC9sx2/EDwmX1LQnQHAkedED2gJ4Auo4WPYHrQWpJnzZHJHKgkicMpGQynINBQtABQAUAFABQAUAFABQAUAFABQAUAJJJHEhklcKoGSzHAFAH0p+w9/wSM/b9/4KE3Npf8A7PnwLu4PC9yw3fEDxaX03QkQnG9J3QvdgEYItY5mB6gdaCXJI/a//gnp/wAGvX7Gn7Lktj8Rf2qb5fjT40gKypa6xp4g8O6fJwcR6eWf7UQcjfdNIjYVlhiYUEObZ+m1ra21jbR2VlbxwwwxhIookCqigYCgDgADgAUEElABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFACMqupR1BBGCCOCKAPiP9sL/g3o/4JfftgzXfiK9+CB+Hnia7bfJ4n+F86aTK7kks0lqEeymZictJJA0h/vjNBSk0fmT+0/8A8GjP7X/w/a51r9lH4+eEviLp6Kzx6P4jhfQtUxn5YkYGa2nbHV3e3U+goLU11PgP9oL/AIJq/wDBQX9laS5b4+/sa/EHQbOzGbrWodAfUdLjHvf2PnWo6H/lrmgpNM8MttQsL0Zs72GX18uQN/KgZNQAUAFABQAUAFAEN1qFhZDN5ewxZ6eZIFz+dAHun7Pv/BNP/goP+1TJbN8Av2NPiDrtneDNrrU+gvp2mSj1W/vvJtT17S5oFdI+/P2YP+DRn9r74gNba1+1d8ffCfw609wryaP4bgk13VMZ+aJ2JhtoGx0dHuFHoaCHNdD9Nf2Pf+Der/gl/wDsezWniKx+CB+IXia0bfH4n+KEyatKjggq0dqUSzhZSMrJHAsg/vmglybPtxVVFCqoAAwAB0oJFoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA8t+NX7D37GX7SFxJffH79lD4c+M7uVSrX/AIl8GWV5cj3WaWIyKfcMDQO7R8z/ABB/4Nsv+COXj9prmL9lWfQLmZs/aPDPjbWLNU/3YRdGAD28vFA+aR474i/4NF/+CamsXDz6N8XvjXoyn7kFh4p0yVF/8CdNlYj6tQPnZyd9/wAGeX7Gzy50v9rz4vRR/wB25XR5G/NbJP5UBzsLH/gzy/Y2SXOqftefF6WP+7bLo8Tfm1k/8qA52dZ4d/4NF/8Agmpo9wk+s/F7416yq/egv/FOmRI3/gNpsTAfRqA52exfD7/g20/4I5eAGhuJP2VZtfuYTn7R4m8baxeLJ/vQtdCA/Ty8UC5pH0z8Ff2IP2NP2b7iO9+AH7KPw58GXUahRfeGvBllZ3De7TRRCRj7liaCbtnqNABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//Z";
                user.APIKey = apiKey;
                var result = await _userManager.CreateAsync(user, Input.Password);

                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    await CreateAccount(user);

                    var userId = await _userManager.GetUserIdAsync(user);
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", new { email = Input.Email, returnUrl = returnUrl });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }

        private async Task CreateAccount(ApplicationUser user)
        {
            // Create default wallet for new registered user
            Wallet wallet = new()
            {
                ApplicationUser = user
            };
            _context.Add(wallet);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Created account for new user with ID {accountId}", user.NormalizedEmail);
        }

        private ApplicationUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<ApplicationUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(ApplicationUser)}'. " +
                    $"Ensure that '{nameof(ApplicationUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        private IUserEmailStore<ApplicationUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<ApplicationUser>)_userStore;
        }
    }
}
